apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uploads
  namespace: gestion-produits-prod
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
