apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uploads
  namespace: gestion-produits-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
