apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-uploads-dev
  namespace: gestion-produits-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 2Gi
