apiVersion: v1
kind: Secret
metadata:
  name: gestion-produits-dev-secret
  namespace: gestion-produits-dev
type: Opaque
stringData:
  DB_NAME:     gestion_produits
  DB_USER:     gestion_user
  DB_PASSWORD: Epsi2026!Dev
