apiVersion: v1
kind: Secret
metadata:
  name: gestion-produits-dev-secret
  namespace: gestion-produits-dev
type: Opaque
stringData:
  DB_NAME:     gestion_produits
  DB_USER:     gpuser
  DB_PASSWORD: gppassword
